pm-flask:
  image: 799617403160.dkr.ecr.us-east-1.amazonaws.com/pm-flask-2
  environment:
    - MYSQL_HOST
    - USE_S3=False 
    - BUCKET=${BUCKET}
    - ENV=local
  volumes:
    # the Z is for selinux:
    - /var/lib/photo_mapper:/app/photo_mapper/static/img:Z
    
pm-nginx:
  image: 799617403160.dkr.ecr.us-east-1.amazonaws.com/pm-nginx:${NGINX_TAG}
  links:
    - pm-flask
  ports:
    - "80:80"
